### PR TITLE
Add support for permanent links

### PR DESCRIPTION
**Pull request by toehead2001**
This will look for an `s` parameter on the url, and if found, will pre-populate the keyword textbox with the found value.

For example:
```
https://forums.getpaint.net/topic/15260-plugin-index/?s=Grid
```

This is useful when people ask about a certain type of plugins.  Like, "Are there any Grid plugins?" or "Are there any alignment plugins?".

On the forum we can cascade the the parameter something like this:
```
iframe.src = new URL(window.location).searchParams.has('s')
	? `https://mattw.io/pdn-plugin-index/${window.location.search}`;
	: 'https://mattw.io/pdn-plugin-index';
```

### CODE REVIEW

**Comment by mattwright324** [comment]
Nice idea! Think it'd be cool to expand it to all search options? Wouldn't be too hard and could even make a 'share this search' link available in the page somewhere. I've done similar stuff for my other apps

Query parse:
https://github.com/mattwright324/youtube-geofind/blob/master/js/youtube-geofind-v6.js#L1655-L1737
Share link:
https://github.com/mattwright324/youtube-geofind/blob/master/js/youtube-geofind-v6.js#L1430

**Comment by toehead2001** [comment]
> Think it'd be cool to expand it to all search options? Wouldn't be too hard and could even make a 'share this search' link available in the page somewhere.

Yeah, it could be cool. Like if you wanted to link to all plugins by XXXX author.

I'm thinking the Checkbox groups (Type, Status, Compatibility) should use Integer bitwise flags.  The dropdowns can just use strings.

I'll work on this tonight.

**Comment by mattwright324** [comment]
Looks pretty cool. However, I think there will be some issues with the query parameters when trying to do it like your first example:

```
https://forums.getpaint.net/topic/15260-plugin-index/?s=Grid
```

Since they are different domains I believe the index site will not be able to read the URL of its parent. Though I think we can work around that by forwarding/appending the query to the iframe src url on the forum integration bit.

https://github.com/mattwright324/pdn-plugin-index#forum-integration

```
iframe.src = "https://mattw.io/pdn-plugin-index" + window.location.search;
```

**Review by mattwright324 — APPROVED** [review]
Looks good. Permalink iframe check works too, modified the iframe src on the plugin forum post with inspect element to point to my localhost and it built the permalink with the correct URL.

**Comment by mattwright324** [comment]
I guess you could also update the README.md forum integration example too for the needed change. I'd probably do it more like this.

```js
iframe.src = "https://mattw.io/pdn-plugin-index" + (window.location.search || "");
```

**Comment by toehead2001** [comment]
According to the spec documentation and through testing, `window.location.search` will always return a string, so the null check shouldn't be needed.

**Comment by toehead2001** [comment]
I think we ready to merge this, no?

**Comment by mattwright324** [comment]
I think its good unless you were waiting on input from Scott, are you able to edit the forum post with the js change or does he have to?

**Comment by toehead2001** [comment]
> you able to edit the forum post with the js change

Yep, I've already made the change.

> unless you were waiting on input from Scott

I'm going to take his silence to mean that he trusts us do a good job  😉

**Comment by mattwright324** [comment]
Awesome, it works!

https://forums.getpaint.net/PluginIndex?keywords=Blur&author=All+Authors+&type=1&status=64&compat=4&order=title&menu=All+Menus+&release=0

**Comment by Sigillatus** [comment]
| I'm going to take his silence to mean that he trusts us do a good job 😉

Yep. I'm following this. You guys have done an excellent job figuring it out :)

**Pull request merged**
